C_OBJS=micro_booter.o test.o cache_tests.o
ASM_OBJS=cos_asm_scheduler.o inv.o
COMPONENT=microbench.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
