C_OBJS=micro_booter.o bench.o rpc.o mem_mgr.o
ASM_OBJS=cos_asm_scheduler.o inv.o
COMPONENT=netperf.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
